### ISSUE TITLE
`hermes create channel ibc-0 basecoin-0 --port-a transfer --port-b transfer` fails

### ISSUE THREAD

**Issue by plafer** [informalsystems/basecoin-rs#54] opened 2022-05-05 15:20 UTC
`basecoin` chain fails in `ConnectionOpenTry` part of the handshake:

>IBC module error
>
>Caused by:
>    ICS03 connection error
>
>    Caused by:
       0: error verifying connnection state
       1: tendermint error
       2: ics23 commitment error
       3: proof verification failed

backtrace:

```shell
thread '<unnamed>' panicked at 'not implemented: RevertibleStore doesn't support delete operations yet!', src/app/store/mod.rs:360:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: <tendermint_basecoin::app::store::RevertibleStore<S> as tendermint_basecoin::app::store::Store>::delete
             at ./src/app/store/mod.rs:360:9
   3: <tendermint_basecoin::app::store::RevertibleStore<S> as tendermint_basecoin::app::store::Store>::reset
             at ./src/app/store/mod.rs:385:43
   4: <tendermint_basecoin::app::store::SharedStore<S> as tendermint_basecoin::app::store::Store>::reset
             at ./src/app/store/mod.rs:255:9
   5: <tendermint_basecoin::app::BaseCoinApp<S> as tendermint_abci::application::Application>::deliver_tx
             at ./src/app/mod.rs:259:25
   6: <A as tendermint_abci::application::RequestDispatcher>::handle
             at /Users/plafer/.cargo/registry/src/github.com-1ecc6299db9ec823/tendermint-abci-0.23.5/src/application.rs:132:69
   7: tendermint_abci::server::Server<App>::handle_client
             at /Users/plafer/.cargo/registry/src/github.com-1ecc6299db9ec823/tendermint-abci-0.23.5/src/server.rs:114:28
   8: tendermint_abci::server::Server<App>::spawn_client_handler::{{closure}}
             at /Users/plafer/.cargo/registry/src/github.com-1ecc6299db9ec823/tendermint-abci-0.23.5/src/server.rs:91:39
```

# To reproduce
1. Set up basecoin chain & `gaiad` chain as indicated in README.md
2. run `hermes create channel ibc-0 basecoin-0 --port-a transfer --port-b transfer`

**Comment by hu55a1n1** [comment] 2022-05-11 09:11
I am able to reproduce this with the `phase6` branch. I have a feeling that this is caused due to a proto version mismatch, so currently working on updating basecoin's proto defs. I think I also figured out why this wasn't showing up on the CI and it seems the CI was always testing against a specific branch of ibc-rs which was previously required since basecoin depended on some ibc-rs code that wasn't merged at the time.

**Closed** 2022-05-24 12:46 UTC
Labels: bug
